CREATE TABLE IF NOT EXISTS public.PL (
    player_id BIGINT,
    player_name VARCHAR(255),
    club VARCHAR(255),
    nationality VARCHAR(100),
    position VARCHAR(50),
    appearances BIGINT,
    minutes BIGINT,
    goals BIGINT,
    assists BIGINT,
    shots BIGINT,
    shots_on_target BIGINT,
    conversion_pct DOUBLE PRECISION,
    big_chances_missed BIGINT,
    hit_woodwork BIGINT,
    offsides BIGINT,
    touches BIGINT,
    passes BIGINT,
    successful_passes BIGINT,
    passes_pct DOUBLE PRECISION,
    crosses BIGINT,
    successful_crosses BIGINT,
    crosses_pct DOUBLE PRECISION,
    fthird_passes BIGINT,
    successful_fthird_passes BIGINT,
    fthird_passes_pct DOUBLE PRECISION,
    through_balls BIGINT,
    carries BIGINT,
    progressive_carries BIGINT,
    carries_ended_with_goal BIGINT,
    carries_ended_with_assist BIGINT,
    carries_ended_with_shot BIGINT,
    carries_ended_with_chance BIGINT,
    possession_won BIGINT,
    dispossessed BIGINT,
    clean_sheets BIGINT,
    clearances BIGINT,
    interceptions BIGINT,
    blocks BIGINT,
    tackles BIGINT,
    ground_duels BIGINT,
    gduels_won BIGINT,
    gduels_pct DOUBLE PRECISION,
    aerial_duels BIGINT,
    aduels_won BIGINT,
    aduels_pct DOUBLE PRECISION,
    goals_conceded BIGINT,
    xgot_conceded BIGINT,
    own_goals BIGINT,
    fouls BIGINT,
    yellow_cards BIGINT,
    red_cards BIGINT,
    saves BIGINT,
    saves_pct DOUBLE PRECISION,
    penalties_saved BIGINT,
    clearances_off_line BIGINT,
    punches BIGINT,
    high_claims BIGINT,
    goals_prevented DOUBLE PRECISION,
    goal_contributions BIGINT,
    shot_accuracy DOUBLE PRECISION,
    fair_play DOUBLE PRECISION,
    defensiveness BIGINT,
    aerial_threat DOUBLE PRECISION,
    saves_per_conceded DOUBLE PRECISION,
    most_similar_player VARCHAR(255),
    similarity_score DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS public.player_similarity (
    player_id BIGINT,
    player_name VARCHAR(255),
    similar_player_1 VARCHAR(255),
    similarity_score_1 DOUBLE PRECISION,
    similar_player_2 VARCHAR(255),
    similarity_score_2 DOUBLE PRECISION,
    similar_player_3 VARCHAR(255),
    similarity_score_3 DOUBLE PRECISION
);
