{
 "title": "EPL",
 "time": { "from": "2025-06-26T19:30:37.558Z", "to": "2025-06-27T07:30:37.558Z" },
 "panels": [
  {
   "title": "Top 10 Goal Contributors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"Player Name\" AS player,\r\n  \"Goals\",\r\n  \"Assists\"\r\nFROM \"PL\"\r\nORDER BY \"Goal Contributions\" DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Midfielders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"Player Name\",\r\n\"Assists\",\r\n\"Passes%\",\r\n\"Through Balls\",\r\n\"Carries\",\r\n\"fThird Passes %\"\r\n from \"PL\" \r\nORDER BY \"Passes%\" desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Defenders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"Player Name\", \r\n\"Possession Won\",\r\n\"Interceptions\",\r\n\"Clearances\",\r\n\"Blocks\",\r\n\"Tackles\",\r\n\"gDuels %\",\r\n\"aDuels %\" from \"PL\" \r\norder by \"Defensiveness\" desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Goalies",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"Player Name\",\r\n\"Saves per conceded\" from \"PL\" \r\nwhere \"Saves per conceded\">0\r\nOrder by \"Saves per conceded\" desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Similar Player Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"Player Name\", \"Most Similar Player\" FROM \"PL\"\r\nORDER BY \"Similarity Score\" DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Fair players",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "Select \"Player Name\" from \"PL\" ORDER BY \"Fair Play\" desc LIMIT 10"
    }
   ]
  }
 ]
}